#!/usr/bin/env bash
# Installs nginx on your web-01 server
# Nginx should be listening on port 80
# Server  pageshould  return a Hello World string
#

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# start nginx service
sudo service nginx start

# allow nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user permission/ ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup the default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Create a new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Restar nginx
sudo service nginx restart

echo -e "\nCompleted. ✅\n"
