#!/usr/bin/env bash

# The script displays the pid, along wth process name
# cannot use ps
# Use pgrep to find the PIDs of processes containing the word "bash" in their name
# -l: Show process name along with PID

pgrep -l bash
