#!/usr/bin/env bash
# Scrpt displays to infinity and beyond indefinetely
# with a sleep 2 in between each iterarion

trap 'echo "I am invincible!!!"' 15
while true; do
	echo "to infinity and beyond"
	sleep 2
done
