#!/usr/bin/env bash

# Displays "Best school" 10 times using a while loop

counter=0

# While loop to display "Best School" 10 times
while [ $counter -lt 10 ]
do
    echo "Best School"
    ((counter++))
done
