#!/bin/env bash

# Retrieve all IPv4 addresses assigned to active network interfaces
ipv4_addresses=$(ip -4 addr show | grep inet | awk '{print $2}' | cut -d'/' -f1)

# Display each IPv4 address
for ip in $ipv4_addresses; do
    echo "$ip"
done
