#!/bin/env bash

# Check if running with root privileges
if [ "$(id -u)" -ne 0 ]; then
    echo "Please run the script with sudo or as root"
    exit 1
fi

# Start listening on port 98
nc -l 127.0.0.1 98
